In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [73]:
df = pd.read_csv("sales.csv")

In [74]:
df.shape

(14, 6)

In [75]:
df.head(14)

ID    Age  Income  Gender Marital Status Buys
0    1    <21    High    Male         Single   No
1    2    <21    High    Male        Married   No
2    3  21-35    High    Male         Single  Yes
3    4    >35  Medium    Male         Single  Yes
4    5    >35     Low  Female         Single  Yes
5    6    >35     Low  Female        Married   No
6    7  21-35     Low  Female        Married  Yes
7    8    <21  Medium    Male         Single   No
8    9    <21     Low  Female        Married  Yes
9   10    >35  Medium  Female         Single  Yes
10  11    <21  Medium  Female        Married  Yes
11  12  21-35  Medium    Male        Married  Yes
12  13  21-35    High  Female         Single  Yes
13  14    >35  Medium    Male        Married   No

In [76]:
df.describe

<bound method NDFrame.describe of     ID    Age  Income  Gender Marital Status Buys
0    1    <21    High    Male         Single   No
1    2    <21    High    Male        Married   No
2    3  21-35    High    Male         Single  Yes
3    4    >35  Medium    Male         Single  Yes
4    5    >35     Low  Female         Single  Yes
5    6    >35     Low  Female        Married   No
6    7  21-35     Low  Female        Married  Yes
7    8    <21  Medium    Male         Single   No
8    9    <21     Low  Female        Married  Yes
9   10    >35  Medium  Female         Single  Yes
10  11    <21  Medium  Female        Married  Yes
11  12  21-35  Medium    Male        Married  Yes
12  13  21-35    High  Female         Single  Yes
13  14    >35  Medium    Male        Married   No>

In [77]:
df["Buys"].value_counts()

Yes    9
No     5
Name: Buys, dtype: int64

In [78]:
df.head()

ID    Age  Income  Gender Marital Status Buys
0   1    <21    High    Male         Single   No
1   2    <21    High    Male        Married   No
2   3  21-35    High    Male         Single  Yes
3   4    >35  Medium    Male         Single  Yes
4   5    >35     Low  Female         Single  Yes

In [79]:
# Preprocessing

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = df.apply(le.fit_transform)

In [80]:
df

ID  Age  Income  Gender  Marital Status  Buys
0    0    1       0       1               1     0
1    1    1       0       1               0     0
2    2    0       0       1               1     1
3    3    2       2       1               1     1
4    4    2       1       0               1     1
5    5    2       1       0               0     0
6    6    0       1       0               0     1
7    7    1       2       1               1     0
8    8    1       1       0               0     1
9    9    2       2       0               1     1
10  10    1       2       0               0     1
11  11    0       2       1               0     1
12  12    0       0       0               1     1
13  13    2       2       1               0     0

In [81]:
df = df.drop(['ID'],axis =1)

In [93]:
df.head()

Age  Income  Gender  Marital Status  Buys
0    1       0       1               1     0
1    1       0       1               0     0
2    0       0       1               1     1
3    2       2       1               1     1
4    2       1       0               1     1

In [82]:
#Independent and Dependent variables
X = df.iloc[:,:-1].values

y = df.iloc[:,-1].values

In [83]:
X

array([[1, 0, 1, 1],
       [1, 0, 1, 0],
       [0, 0, 1, 1],
       [2, 2, 1, 1],
       [2, 1, 0, 1],
       [2, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 2, 1, 1],
       [1, 1, 0, 0],
       [2, 2, 0, 1],
       [1, 2, 0, 0],
       [0, 2, 1, 0],
       [0, 0, 0, 1],
       [2, 2, 1, 0]])

In [84]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [85]:
#Train and Test Data

from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,train_size=0.25,random_state=0)

In [86]:
#Model Building

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy' , random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [87]:
y_pred = classifier.predict(X_test)

In [88]:
y_pred

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [90]:
from sklearn.metrics import confusion_matrix , accuracy_score

#Confusion Matrix
cm = confusion_matrix(y_test , y_pred)
cm

array([[3, 0],
       [5, 3]], dtype=int64)

In [91]:
#Accuracy Score
accuracy_score(y_test , y_pred)

0.5454545454545454

In [95]:
classifier.predict([[0,0,1,1]])

array([1])

In [89]:
classifier.predict([[1,1,0,0]])

array([0])

## Conclusion

Root Node for the decision tree is 'Age'

Predicted class for input [Age>21 , Income = Low , Gender = Female , Marital Status = Married]
i. e. [1,1,0,0] is No[0]